### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by bhickey** [kitsook/ChaCha20#3]
Hi,

Could you slap a license on this implementation? I'd like to use it in a BSD licensed game. I assume you want it shared, unless quick and dirty is a warning. ;)

Cheers,
Brendan

**Comment by kitsook** [comment]
Hi Brendan,

This really is a "quick and dirty" implementation, meaning that I haven't done much testing on it. ;P

e.g. there seems to be different implementations (IETF draft vs original) of the block counter size out there.  I didn't have time to [figure it out yet](https://github.com/kitsook/ChaCha20/blob/master/ChaCha20/src/net/clarenceho/util/ChaCha20.java#L125).

I implemented the code out of curiosity and that is why I didn't bother to put any license on it.  Feel free to reuse the code.  Better yet, fork and PR if you find and fix any bugs.

Regards,
Clarence

**Comment by kitsook** [comment]
added license 067145da5f6ee272683db8c486e54a658c6081ba
